name: MyFirstSteps
favicon: null
layout_spectrum: 0.88856
typography_spectrum: 0.44575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#716c68'
    - '#83a3c9'
    - '#030303'
    - '#d7d5c8'
    - '#434345'
  brandStrength: 0.9375
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
