name: MyFirstSteps
favicon: null
layout_spectrum: 0.726611124817282
typography_spectrum: 0.45836930396035314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7923088723327965
  lightness: 0.7775195941794664
  saturation: 0.6903193818870932
  rhythmicContrast: 0.20788290933705866
purpose: []
